- hosts: all
  tasks:

  - name: "show distribution major version"
    debug:
      msg: "ansible_distribution_major_version={{ansible_distribution_major_version}}"

  - name: "Install htop package"
    package:
      name: htop
      state: present
    when: ansible_distribution_major_version == '20'

  - name: "Install netcat package"
    package:
      name: netcat
      state: present
    when: ansible_distribution_major_version == '18'

  - name: "create random user with one of foo, bar, baz"
    user:
      name: "{{item}}"
      state: present
    with_random_choice:
      - foo
      - bar
      - baz
