# config.vm.provision "shell", inline: <<-SHELL
#   apt update
#   apt install -y nginx
# SHELL
- hosts: all
  vars:
    users:
    - name: ivoputzer
      comment: Ivo von Putzer Reibegg
      password: $6$shrKLeidKxVrmU4U$ebJ1FEf1jPt/tNKOuroLTvCkCCvIJkO883mg3Vil5IEiFljkMRjJoTd.nSC04r3xnTq9/BC2aB/Pva/pMwEZw1
      state: present
  tasks:
  - name: Install nginx package
    package:
      name: nginx
      state: present
  roles:
  - role: users
    tags: [system, users, ssh]
