# config.vm.provision "shell", inline: <<-SHELL
#   apt update
#   apt install -y nginx
# SHELL
- hosts: all
  vars:
    users:
    - name: ivoputzer
      comment: Ivo von Putzer Reibegg
      password: $6$shrKLeidKxVrmU4U$ebJ1FEf1jPt/tNKOuroLTvCkCCvIJkO883mg3Vil5IEiFljkMRjJoTd.nSC04r3xnTq9/BC2aB/Pva/pMwEZw1
      state: present
  tasks:
  - name: Install nginx package
    package:
      name: nginx
      state: present
  - name: Add users with primary group sudo
    ansible.builtin.user:
      name: "{{ item.name }}"
      comment: "{{ item.comment }}"
      create_home: true
      group: sudo
      password: "{{ item.password }}"
      shell: /bin/bash
      state: "{{ item.state }}"
    with_items: "{{ users }}"

  - name: "add authorized_key without validation the certificate"
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "https://github.com/{{ item.name }}.keys"
      validate_certs: false
    with_items: "{{ users }}"
